### PR TITLE
Add require for use-package

### PR DESCRIPTION
**Pull request by kixi**
I had to require use-package here to make it work on my machine (Emacs 27.1 / Linux). I hope this helps to improve. I do not know Emacs Lisp, so feel free to reject this PR if it is total crap.

### CODE REVIEW

**Comment by plexus** [comment]
How are you loading corkey? Normally you would load it via use-package, meaning use-package would be loaded by then.

**Comment by kixi** [comment]
without the require I get this error:
`Error (use-package): corkey/:catch: Symbol’s value as variable is void: evil
`

Actually I used the init.el you provided in the documentation
```
(use-package corgi-packages
  :straight (corgi-packages
             :type git
             :host github
             :repo "kixi/corgi-packages"))

(add-to-list #'straight-recipe-repositories 'corgi-packages)

(let ((straight-current-profile 'corgi))
  (use-package corgi-defaults)
  (use-package corgi-editor)
  (use-package corgi-emacs-lisp)
  (use-package corgi-commands)
  (use-package corgi-clojure)
  (use-package corgi-stateline)
  (use-package corkey
    :config
    (corkey-mode 1)
    (corkey/install-bindings 'my-keys)))


```

**Comment by magthe** [comment]
I'm seeing this error on startup of a brand new install as well.

**Comment by plexus** [comment]
Hi @kixi , @magthe . Corgi kind of got stalled in a half finished state, and I'm not yet sure when I will have time to work on it again, or if I will abandon the effort. However, if you want to help make Corgi a reality and we can get a small team together to pull it over the finish line then I would be interested to lead that effort. If so I will invite you to the Lambda Island discord and we can set up a call to discuss how to organize things.

**Comment by magthe** [comment]
@plexus sorry to have to say that I was only trying it out as I heard of it for the first time today (found a link from a post on Reddit). I'm also not much of an "emacs configurator".

So while I like the idea of Corgi, I am afraid I don't feel up to the task of making it a reality at this point.

**Comment by plexus** [comment]
Could you share the link please? Corgi has not been publicly announced so I'm surprised people are talking about it.

**Comment by magthe** [comment]
https://www.reddit.com/r/emacs/comments/mwr0op/are_there_any_minimal_evil_distributions/gvkaqe5?utm_source=share&utm_medium=web2x&context=3

**Comment by christiaan-janssen** [comment]
Can confirm. After a new install I get the same error. This fix solves the problem.

**Comment by plexus** [comment]
Thanks!

**Pull request merged**
