### PR TITLE
Added "scheme-mode" support with "geiser".

### PR DESCRIPTION
**Pull request by CoderPrans**
Hi, thanks for corgi. I really enjoy using it. 

I've added some extra keys and signals and suggest changing normal mode stateline color from 'orange' to 'gray' for people who have trouble telling the difference between orange and green (like me). 

Changes include:
1. signals: `scheme-mode` to support global eval key sequences for scheme with "geiser"
2. keys: 
    i. 'Spc b k' to `kill-buffer` list buffers and select to kill.
    ii. 'Spc p k' to `projectile-kill-buffers` kill all buffers of current project (quit project).
3. stateline: changed `corgi-stateline-normal-bg` from 'orange' -> 'gray'

### CODE REVIEW

**Comment by plexus** [comment]
Looks good! do these bindings match spacemacs? (they don't have to, but it's the general baseline we start from unless we have good reason to do something else)

**Comment by CoderPrans** [comment]
Wow, thanks for merging my PR, @plexus. 
Sorry, I don't know if the bindings match spacemacs, never used spacemacs.

**Comment by plexus** [comment]
Ok, I may revert these, we already have `d` for `delete` buffer, e.g. `SPC b d`, we can add `SPC p d`

**Comment by plexus** [comment]
Seems they don't have bindings for `SPC b k`, at least not in their docs, and there is a difference between kill-buffer and kill-this-buffer, so I think we can leave this in

https://www.spacemacs.org/doc/DOCUMENTATION.html#buffers-manipulation-key-bindings

**Pull request merged**
